import java.nio.file.Files
import java.nio.file.Paths

if(JavaVersion.current().ordinal() < JavaVersion.VERSION_17.ordinal()){
    throw new Exception("!!! YOU MUST USE JAVA 17 OR ABOVE TO COMPILE AND RUN MINDUSTRY !!! Read the README. Your version: ${System.properties["java.version"]}")
}

include 'core', 'server', 'annotations', 'tools', 'tests'

def workspacePath = null
if (System.env["MINDURKA_WORKSPACE"] == null) {
    def path = Paths.get("${rootProject.projectDir}").parent.resolve("workspace.meta")
    if (Files.exists(path)) {
        workspacePath = path.parent
    } else {
        throw new IllegalStateException("could not find workspace. Make sure 'MINDURKA_WORKSPACE' environment variable is set.")
    }
} else {
    workspacePath = Paths.get(System.env["MINDURKA_WORKSPACE"])
}
gradle.ext.workspacePath = workspacePath

if(!hasProperty("noLocalArc")){
    if(new File(rootDir.parent, 'arc').exists()){
        println("Compiling with localArc")
        includeBuild("../arc")
    }else{
        throw RuntimeException("Workspace configuration is incorrect!")
    }

    if(new File(rootDir.parent, 'Mindustry-Debug').exists()){
        include(":debug")
        project(":debug").projectDir = new File(rootDir.parent, "Mindustry-Debug")
    }
}else{
    println("Not including local repositories.")
}
